export const GET_EMAIL_LIST_REQUEST = "GET_EMAIL_LIST_REQUEST";
export const GET_EMAIL_LIST_SUCCESS = "GET_EMAIL_LIST_SUCCESS";
export const GET_EMAIL_LIST_FAILURE = "GET_EMAIL_LIST_FAILURE";

export const GET_APP_DATA_REQUEST = "GET_APP_DATA_REQUEST";
export const GET_APP_DATA_SUCCESS = "GET_APP_DATA_SUCCESS";
export const GET_APP_DATA_FAILURE = "GET_APP_DATA_FAILURE";

export const SET_BODY = "SET_BODY";

export const SET_SORTED = "SET_SORTED";
export const SET_FILTER = "SET_FILTER";